#!/bin/bash
# shellcheck disable=SC2015  # `[ cond ] && ok || ko` — ok/ko always succeed, safe idiom
# HTTP-publishing e2e — run on pve-node as root. Provisions a real dev VM, starts
# two web servers on it (:80 and :8080 with distinct markers), attaches
# multiple domains via the API (contract v0.29.0: POST /vms/{id}/domains, one
# domain per port), verifies each FQDN serves ITS port's content via the origin
# :443 SNI path (the Cloudflare leg is unreachable from pve-node — hairpin NAT),
# exercises the released-name reservation (release → reserved → revive →
# immediate return) and the per-VM platform-subdomain cap, then force-deletes
# and confirms teardown removed EVERY vhost before IP release. Cleans up the
# VM regardless.
#
# Do not edit this file while a run is in progress. Bash reads a script
# incrementally by byte offset, so an edit under a running shell shifts what it
# reads next and the run diverges from the file — a 2026-08-09 run failed that
# way mid-verification and its result had to be discarded. Let the run finish,
# or kill it first; the EXIT trap deletes the VM either way.
set -uo pipefail
BASE="${BASE:-https://pickle.pusan.ac.kr/api/v1}"
# Signup requires consent to every current terms version (422 otherwise).
# Built once from the public endpoint so version bumps never break the smoke.
CONSENTS_JSON=$(curl -fsS "$BASE/meta/terms" 2>/dev/null | jq -c '[.[] | {docType, version}]' 2>/dev/null)
[ -n "$CONSENTS_JSON" ] || CONSENTS_JSON='[]'

CTID="${CTID:-101}"
TS=$(date +%s)-$RANDOM
# Every domain this run creates shares this prefix, so one grep over pickle.d
# counts (and later proves the disappearance of) the whole set.
SUB="e2e-${TS}"
SUB2="${SUB}-b"
# Platform root to publish under. Overridable so the smoke can exercise a second
# root the moment one exists, without editing the script.
ROOT="${ROOT:-pusan.dev}"
USER_EMAIL="http-${TS}@pusan.ac.kr"; USER_PW="http-pass-${TS}!"
seed_env(){ pct exec "$CTID" -- sh -c "grep '^$1=' /etc/pickle/api.env | cut -d= -f2-"; }
ORGADMIN_EMAIL="$(seed_env PICKLE_SEED_ORGADMIN_EMAIL)"; ORGADMIN_EMAIL="${ORGADMIN_EMAIL:-orgadmin@pnuops.com}"; ORGADMIN_PW="$(seed_env PICKLE_SEED_ORGADMIN_PASSWORD)"
SYSADMIN_EMAIL="$(seed_env PICKLE_SEED_SYSADMIN_EMAIL)"; SYSADMIN_EMAIL="${SYSADMIN_EMAIL:-admin@pnuops.com}"; SYSADMIN_PW="$(seed_env PICKLE_SEED_SYSADMIN_PASSWORD)"
B=$(mktemp); RT_DIR=$(mktemp -d)   # RT_DIR: sudo-mode token cache (see reauth below)
# Always-run cleanup (EXIT trap): a mid-run failure after the VM exists must
# not leak a real guest + IP — force-delete best-effort, mirroring smoke-provisioning.
VM=""; VM_DELETED=0
cleanup(){
  local rc=$?
  if [ -n "$VM" ] && [ "$VM_DELETED" != 1 ]; then
    echo "-- cleanup: force-deleting leftover VM $VM --"
    local at
    at=$(curl -sS -X POST "$BASE/auth/login" -H 'Content-Type: application/json' \
      -d "{\"email\":\"$SYSADMIN_EMAIL\",\"password\":\"$SYSADMIN_PW\"}" | jq -r '.accessToken // empty')
    if [ -n "$at" ] && [ -n "${VNAME:-}" ]; then
      # This is the last chance to avoid leaking a real guest and its IP, so the
      # response code decides what gets printed — a swallowed failure here reads
      # as "cleaned up" while the VM is still running.
      local dc
      dc=$(curl -sS -o /dev/null -w '%{http_code}' -X POST "$BASE/admin/vms/$VM/force-delete" \
        -H "Authorization: Bearer $at" -H 'Content-Type: application/json' \
        -d "{\"confirmName\":\"$VNAME\",\"reason\":\"smoke cleanup (trap)\"}")
      if [ "$dc" = 202 ]; then
        echo "-- cleanup: force-delete accepted (202) --"
      else
        echo "-- cleanup: force-delete REJECTED (http=${dc:-none}); manual cleanup needed (vm id $VM) --" >&2
      fi
    else
      echo "-- cleanup: could not obtain admin token or VM name; manual cleanup needed (vm id $VM) --" >&2
    fi
  fi
  rm -f "$B"; rm -rf "$RT_DIR"
  exit "$rc"
}
trap cleanup EXIT
P=0; F=0; ok(){ echo "PASS  $1"; P=$((P+1)); }; ko(){ echo "FAIL  $1"; F=$((F+1)); }
req(){ local n="$1" e="$2"; shift 2; local c; c=$(curl -sS -o "$B" -w '%{http_code}' "$@"); if [ "$c" = "$e" ]; then ok "$n ($c)"; return 0; else ko "$n (expected $e got $c)"; head -c 300 "$B"; echo; return 1; fi; }
# Sudo-mode reauth: the password-reveal / VM-delete / settings / ssh-key /
# group-member endpoints answer 403 REAUTH_REQUIRED without a fresh password
# proof (X-Reauth-Token). The token is per-account and multi-use for 10 minutes,
# and POST /auth/reverify is rate-limited per IP and per account, so cache it
# per access token instead of minting one per call. A password change bumps the
# token version (killing both tokens), but that also forces a re-login here, so
# the new access token becomes a new cache key and the cache self-heals.
# The cache is FILE-backed on purpose: every call site invokes reauth from a
# command substitution (a subshell), so an in-memory array would be written in
# the subshell and thrown away — each protected call would then mint a fresh
# token and the per-IP reverify limit (every account here shares this host's
# egress IP) would start answering 429 with an empty token, i.e. a spurious
# REAUTH_REQUIRED failure. Entries expire well inside the 10-minute server TTL.
reauth(){ # reauth ACCESS_TOKEN PASSWORD → echoes the X-Reauth-Token value
  local f exp tok
  f="$RT_DIR/$(printf '%s' "$1" | md5sum | cut -d' ' -f1)"
  if [ -s "$f" ]; then
    { read -r exp; read -r tok; } < "$f"
    [ "$SECONDS" -lt "${exp:-0}" ] && { printf '%s' "$tok"; return 0; }
  fi
  tok=$(curl -sS -X POST "$BASE/auth/reverify" -H "Authorization: Bearer $1" \
    -H 'Content-Type: application/json' -d "$(jq -nc --arg p "$2" '{password:$p}')" \
    | jq -r '.reauthToken // empty')
  [ -n "$tok" ] && printf '%s\n%s\n' "$((SECONDS+480))" "$tok" > "$f"
  printf '%s' "$tok"
}
# 'basic' spec preset (first ACTIVE row as fallback) out of GET /vm-flavors
FSEL='(map(select(.name=="basic"))[0] // .[0])'
# VmDetail.publication (singular) became publications[] in v0.29.0 — select one
# domain's slice by FQDN out of the freshest VmDetail in $B.
pub(){ jq -r --arg f "$1" --arg p "$2" '[.publications[] | select(.fqdn==$f)][0] | getpath($p / ".") // empty' "$B"; }
# Poll one domain's route to APPLIED (each domain now carries its own route).
wait_applied(){ # wait_applied FQDN LABEL
  local dl=$((SECONDS+120)) rst=""
  while :; do
    curl -sS -o "$B" "$BASE/vms/$VM" -H "Authorization: Bearer $SAT"
    rst=$(pub "$1" "route.status")
    [ "$rst" = "APPLIED" ] && { ok "$2 route APPLIED ($1)"; return 0; }
    [ "$rst" = "FAILED" ] && { ko "$2 route FAILED: $(pub "$1" "route.lastError")"; return 1; }
    [ "$SECONDS" -ge "$dl" ] && { ko "$2 route not APPLIED in 120s (last=$rst)"; return 1; }
    sleep 5
  done
}
# Origin :443 SNI fetch with the pinned wildcard key; body lands in $B.
origin(){ # origin FQDN → echoes the http code
  local c=""; : >"$B"
  for _ in $(seq 1 6); do
    c=$(curl -sS -o "$B" -w '%{http_code}' -k --pinnedpubkey "sha256//$PIN" --max-time 15 \
      --resolve "$1:443:198.18.1.10" "https://$1/index.html" 2>/dev/null)
    [ "$c" = "200" ] && break; sleep 5
  done
  printf '%s' "$c"
}
vhost_count(){ pct exec 100 -- sh -c "ls /etc/nginx/pickle.d/ | grep -c '$1'" 2>/dev/null; }

echo "== auth =="
req "signup" 202 -X POST "$BASE/auth/signup" -H 'Content-Type: application/json' -d "{\"email\":\"$USER_EMAIL\",\"password\":\"$USER_PW\",\"name\":\"HTTP E2E\",\"consents\":$CONSENTS_JSON}" || exit 1
sleep 2
TOKEN=$(pct exec "$CTID" -- sh -c "grep -o 'token=[A-Za-z0-9_-]*' /var/lib/pickle/mock-mail.log 2>/dev/null | tail -1 | cut -d= -f2")
req "verify-email" 200 -X POST "$BASE/auth/verify-email" -H 'Content-Type: application/json' -d "{\"token\":\"$TOKEN\"}" || exit 1
req "user login" 200 -X POST "$BASE/auth/login" -H 'Content-Type: application/json' -d "{\"email\":\"$USER_EMAIL\",\"password\":\"$USER_PW\"}" || exit 1
SAT=$(jq -r .accessToken "$B")
req "create workspace" 201 -X POST "$BASE/workspaces" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"name\":\"http e2e\",\"kind\":\"TEAM\"}" || exit 1
GID=$(jq -r .id "$B")
req "orgadmin login" 200 -X POST "$BASE/auth/login" -H 'Content-Type: application/json' -d "{\"email\":\"$ORGADMIN_EMAIL\",\"password\":\"$ORGADMIN_PW\"}" || exit 1
AAT=$(jq -r .accessToken "$B")
# the seed org is hidden and GET /orgs filters hidden orgs for USER tokens — list as orgadmin
req "orgs" 200 "$BASE/orgs" -H "Authorization: Bearer $AAT" || exit 1; OID=$(jq -r '.[0].id' "$B")
req "os-images" 200 "$BASE/os-images" -H "Authorization: Bearer $SAT" || exit 1
# The catalog is returned in DISPLAY order (distribution, then release), so the
# first row is a moving target: it was an Ubuntu row until Debian entered the
# catalog and sorted ahead of it. Any row provisions fine, but name the pick so a
# distro-specific failure below is readable instead of looking like flakiness.
TID=$(jq -r '.[0].id // empty' "$B"); INAME=$(jq -r '.[0].name // empty' "$B")
[ -n "$TID" ] && ok "os image = $INAME (id=$TID)" || { ko "no ACTIVE OS image to request with"; exit 1; }
# os-images is a pure OS catalog — the spec axis lives in vm-flavors, and
# POST /requests requires the chosen flavorId alongside the req* specs
req "vm-flavors" 200 "$BASE/vm-flavors" -H "Authorization: Bearer $SAT" || exit 1
FID=$(jq -r "$FSEL.id // empty" "$B"); VC=$(jq -r "$FSEL.vcpu // empty" "$B"); MM=$(jq -r "$FSEL.memoryMb // empty" "$B"); DG=$(jq -r "$FSEL.diskGb // empty" "$B")
[ -n "$FID" ] && ok "flavor id=$FID (${VC}c/${MM}MB/${DG}GB)" || { ko "no ACTIVE vm-flavor"; exit 1; }

echo "== request + approve (the request form carries no domain axis anymore) =="
req "vm-request" 201 -X POST "$BASE/requests" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"type\":\"VM\",\"workspaceId\":$GID,\"orgId\":$OID,\"purpose\":\"HTTP publish e2e\",\"courseOrProject\":null,\"extraNote\":null,\"reqStartDate\":null,\"reqEndDate\":null,\"vm\":{\"imageId\":$TID,\"flavorId\":$FID,\"reqVcpu\":$VC,\"reqMemoryMb\":$MM,\"reqDiskGb\":$DG,\"specReason\":null}}" || exit 1
RID=$(jq -r .id "$B")
req "approve" 200 -X POST "$BASE/admin/requests/$RID/approve" -H "Authorization: Bearer $AAT" -H 'Content-Type: application/json' -d "{\"grantedStartDate\":null,\"grantedEndDate\":null,\"comment\":\"http e2e\",\"vm\":{\"grantedVcpu\":$VC,\"grantedMemoryMb\":$MM,\"grantedDiskGb\":$DG,\"grantedImageId\":$TID,\"nodeId\":null}}" || exit 1
req "vm list" 200 "$BASE/vms?workspaceId=$GID" -H "Authorization: Bearer $SAT" || exit 1
VM=$(jq -r '.content[0].id // empty' "$B"); VNAME=$(jq -r '.content[0].name // empty' "$B")
[ -n "$VM" ] && ok "vm id=$VM name=$VNAME" || { ko "vm id (empty list)"; exit 1; }
curl -sS -o "$B" "$BASE/vms/$VM" -H "Authorization: Bearer $SAT"
PLEN=$(jq -r '.publications | length' "$B")
[ "$PLEN" = "0" ] && ok "publications is an empty array before any domain" || ko "publications=$PLEN before any domain (expected 0)"

echo "== poll RUNNING (<=15m) =="
DL=$((SECONDS+900)); ST=""
while :; do curl -sS -o "$B" "$BASE/vms/$VM" -H "Authorization: Bearer $SAT"; ST=$(jq -r .status "$B"); VIP=$(jq -r '.ipAddress // empty' "$B")
  [ "$ST" = "RUNNING" ] && break
  if [ "$ST" = "ERROR" ] || [ "$ST" = "NEEDS_ADMIN" ]; then ko "provision reached $ST"; jq -r '.statusDetail' "$B"; break; fi
  [ "$SECONDS" -ge "$DL" ] && { ko "not RUNNING in 15m (last=$ST)"; break; }; sleep 10; done
[ "$ST" = "RUNNING" ] && ok "VM RUNNING ip=$VIP" || exit 1

echo "== reveal password + start web servers on VM:80 and VM:8080 =="
curl -sS -o "$B" "$BASE/vms/$VM/password" -H "Authorization: Bearer $SAT" \
  -H "X-Reauth-Token: $(reauth "$SAT" "$USER_PW")"
PWV=$(jq -r '.password // empty' "$B"); [ -n "$PWV" ] && ok "initial password revealed (masked)" || ko "password reveal"
# The guest account is a property of the image, not a constant: ubuntu images
# carry `ubuntu`, debian `debian`, rocky `rocky`. Hardcoding one broke this smoke
# the moment the catalog stopped listing an Ubuntu row first. The reveal answers
# with the password and ITS account in the same response, so the pair used below
# always belongs to THIS VM's image and no catalog reorder can split them.
SSHU=$(jq -r '.sshUsername // empty' "$B")
[ -n "$SSHU" ] && ok "guest account from the reveal ($SSHU)" || ko "sshUsername missing on the password reveal"
# wait ssh
for _ in $(seq 1 18); do nc -z -w5 "$VIP" 22 2>/dev/null && break; sleep 5; done
# the VM password IS the sudo credential (template sudoers demands it) — feed it to
# a single sudo -S via stdin, then probe as the unprivileged user. Two servers
# with DISTINCT markers so per-domain ports are distinguishable end to end.
printf '%s\n' "$PWV" | sshpass -p "$PWV" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 "$SSHU@$VIP" \
  "sudo -S bash -c 'mkdir -p /var/e2e /var/e2e-alt; echo PICKLE-HTTP-E2E-OK > /var/e2e/index.html; echo PICKLE-HTTP-E2E-ALT > /var/e2e-alt/index.html; cd /var/e2e; nohup python3 -m http.server 80 >/tmp/httpd80.log 2>&1 & cd /var/e2e-alt; nohup python3 -m http.server 8080 >/tmp/httpd8080.log 2>&1 & sleep 2' 2>/dev/null; curl -s -o /dev/null -w 'p80:%{http_code} ' http://127.0.0.1:80/index.html; curl -s -o /dev/null -w 'p8080:%{http_code}' http://127.0.0.1:8080/index.html" >"$B" 2>/dev/null
PWV=""
grep -q "p80:200" "$B" && ok "web server up on VM:80" || ko "web server on VM:80 ($(cat "$B"))"
grep -q "p8080:200" "$B" && ok "web server up on VM:8080" || ko "web server on VM:8080 ($(cat "$B"))"
# proxy-agent can reach both VM ports from LXC 100
pct exec 100 -- sh -c "curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 http://$VIP:80/index.html" >"$B" 2>/dev/null
[ "$(cat "$B")" = "200" ] && ok "LXC100 → VM:80 reachable" || ko "LXC100 → VM:80 ($(cat "$B"))"
pct exec 100 -- sh -c "curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 http://$VIP:8080/index.html" >"$B" 2>/dev/null
[ "$(cat "$B")" = "200" ] && ok "LXC100 → VM:8080 reachable" || ko "LXC100 → VM:8080 ($(cat "$B"))"

echo "== first domain: $SUB.$ROOT → VM:80 =="
FQDN1="${SUB}.${ROOT}"
req "create domain 1" 202 -X POST "$BASE/vms/$VM/domains" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"port\":80,\"subdomain\":\"$SUB\",\"rootDomain\":\"$ROOT\"}" || true
[ "$(jq -r '.fqdn // empty' "$B")" = "$FQDN1" ] && ok "fqdn = chosen name ($FQDN1)" || ko "fqdn=$(jq -r '.fqdn' "$B") (expected $FQDN1)"
wait_applied "$FQDN1" "domain 1" || true

echo "== vhost rendered on LXC 100 =="
[ "$(vhost_count "$FQDN1")" -ge 1 ] 2>/dev/null && ok "vhost file present in pickle.d ($FQDN1)" || ko "vhost file missing ($FQDN1)"

echo "== origin chain: LXC100 :443 SNI → 8443 → subdomain vhost → VM:80 =="
# The Cloudflare→pve-node:443 leg is identical infra to opus (externally verified);
# from pve-node that leg can't be curled (hairpin NAT), so validate the NEW segment
# directly: hit LXC100 :443 with the real SNI, exercising ssl_preread → default
# 8443 → the rendered subdomain vhost → proxy_pass to the VM. TLS: the wildcard is
# a Cloudflare Origin CA cert, NOT in the public trust store (plain validation
# gives 000) — so pin the DEPLOYED cert's public key instead (-k disables chain
# checks but --pinnedpubkey still enforces the pin ⇒ a cert regression fails).
# Read the pair the agent is configured to serve for THIS root rather than
# repeating a filename convention here: the agent's map is what actually decides
# which certificate the vhost gets, so pinning anything else could pass while the
# served certificate is a different one.
CERTS_ENV=$(pct exec 100 -- sh -c "grep '^PICKLE_PROXY_AGENT_WILDCARD_CERTS=' /etc/pickle-proxy-agent/agent.env | cut -d= -f2-" 2>/dev/null)
# Split on the FIRST '=' only, like the agent's own parser does — awk -F= would
# truncate a path that itself contains '=' and pin the wrong file.
CERT_PATH=$(printf '%s' "$CERTS_ENV" | tr ',' '\n' \
  | sed -n "s/^[[:space:]]*${ROOT}=//p" | cut -d: -f1)
[ -n "$CERT_PATH" ] && ok "agent has a wildcard certificate for $ROOT" || ko "agent has no wildcard certificate configured for $ROOT"
PIN=$(pct exec 100 -- cat "$CERT_PATH" 2>/dev/null \
  | openssl x509 -pubkey -noout 2>/dev/null | openssl pkey -pubin -outform der 2>/dev/null \
  | openssl dgst -sha256 -binary | base64)
if [ -n "$PIN" ]; then
  C=$(origin "$FQDN1")
  [ "$C" = "200" ] && ok "origin HTTPS 200 via :443 SNI, cert pin OK ($FQDN1)" || ko "origin HTTPS $C (or cert pin mismatch)"
  grep -q "PICKLE-HTTP-E2E-OK" "$B" && ok "served content = VM:80 (PICKLE-HTTP-E2E-OK)" || ko "content mismatch ($(head -c 60 "$B"))"
else
  ko "origin HTTPS (no cert pin)"
  ko "served content (no cert pin)"
fi

echo "== second domain on the SAME VM: $SUB2.$ROOT → VM:8080 =="
FQDN2="${SUB2}.${ROOT}"
req "create domain 2" 202 -X POST "$BASE/vms/$VM/domains" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"port\":8080,\"subdomain\":\"$SUB2\",\"rootDomain\":\"$ROOT\"}" || true
D2=$(jq -r '.domain.id // empty' "$B")
wait_applied "$FQDN2" "domain 2" || true
PLEN=$(jq -r '.publications | length' "$B")
[ "$PLEN" = "2" ] && ok "publications lists both domains" || ko "publications=$PLEN (expected 2)"
if [ -n "$PIN" ]; then
  C=$(origin "$FQDN2")
  [ "$C" = "200" ] && ok "second domain answers via :443 SNI ($FQDN2)" || ko "second domain HTTPS $C"
  # The whole point of per-domain ports: each name must serve ITS backend.
  grep -q "PICKLE-HTTP-E2E-ALT" "$B" && ok "second domain serves VM:8080 content (ALT marker)" || ko "second domain content ($(head -c 60 "$B"))"
  grep -q "PICKLE-HTTP-E2E-OK" "$B" && ko "second domain leaked VM:80 content" || ok "second domain does not leak VM:80 content"
else
  ko "second domain origin (no cert pin)"
fi

echo "== release only the second domain; the first must keep serving =="
req "release domain 2" 202 -X DELETE "$BASE/domains/$D2" -H "Authorization: Bearer $SAT" || true
# vhost removal is async (route apply) — poll its disappearance
TDL=$((SECONDS+90)); V2="?"
while :; do V2=$(vhost_count "$FQDN2"); [ "$V2" = "0" ] && break
  [ "$SECONDS" -ge "$TDL" ] && break; sleep 5; done
[ "$V2" = "0" ] && ok "released domain's vhost removed" || ko "released vhost remains after 90s (count=$V2)"
if [ -n "$PIN" ]; then
  C=$(origin "$FQDN1")
  { [ "$C" = "200" ] && grep -q "PICKLE-HTTP-E2E-OK" "$B"; } \
    && ok "remaining domain still serves after sibling release ($FQDN1)" \
    || ko "remaining domain broken after sibling release (HTTP $C)"
fi
curl -sS -o "$B" "$BASE/vms/$VM" -H "Authorization: Bearer $SAT"
PLEN=$(jq -r '.publications | length' "$B")
[ "$PLEN" = "1" ] && ok "publications shrank to the serving domain only" || ko "publications=$PLEN after release (expected 1)"

echo "== released platform name is reserved, revivable, then returnable =="
curl -sS -o "$B" "$BASE/domains?vmId=$VM" -H "Authorization: Bearer $SAT"
DROW=$(jq -c --arg f "$FQDN2" '[.content[] | select(.fqdn==$f)][0] // empty' "$B")
DSTATUS=$(printf '%s' "$DROW" | jq -r '.status // empty')
{ [ -n "$DROW" ] && [ "$DSTATUS" != "REMOVED" ]; } && ok "released row still holds the name (status=$DSTATUS)" || ko "released row gone or REMOVED ($DSTATUS)"
[ "$(printf '%s' "$DROW" | jq -r '.releasedAt // empty')" != "" ] && ok "releasedAt is set on the reserved row" || ko "releasedAt missing on the reserved row"
[ "$(printf '%s' "$DROW" | jq -r '.reservedUntil // empty')" != "" ] && ok "reservedUntil is server-computed on the reserved row" || ko "reservedUntil missing on the reserved row"
# Re-adding the same name on the same VM revives the reserved row (same id).
req "revive released name" 202 -X POST "$BASE/vms/$VM/domains" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"port\":8080,\"subdomain\":\"$SUB2\",\"rootDomain\":\"$ROOT\"}" || true
RID2=$(jq -r '.domain.id // empty' "$B")
[ "$RID2" = "$D2" ] && ok "revive reused the reserved row (id=$D2)" || ko "revive created a new row (id=$RID2, expected $D2)"
[ "$(jq -r '.domain.releasedAt // empty' "$B")" = "" ] && ok "revive cleared releasedAt" || ko "releasedAt survived the revive"
wait_applied "$FQDN2" "revived domain" || true
# Release again, then DELETE the now-reserved row: same endpoint, second call
# returns the name immediately instead of waiting out the grace.
req "release again" 202 -X DELETE "$BASE/domains/$D2" -H "Authorization: Bearer $SAT" || true
req "return reserved name now" 202 -X DELETE "$BASE/domains/$D2" -H "Authorization: Bearer $SAT" || true
# The returned name is gone from the default listing (removed rows are hidden
# the way they are for admins) and reads REMOVED when asked for explicitly.
curl -sS -o "$B" "$BASE/domains?vmId=$VM" -H "Authorization: Bearer $SAT"
DGONE=$(jq -r --arg f "$FQDN2" '[.content[] | select(.fqdn==$f)] | length' "$B")
[ "$DGONE" = "0" ] && ok "returned name left the default listing" || ko "returned name still listed by default ($DGONE row(s))"
curl -sS -o "$B" "$BASE/domains?vmId=$VM&status=REMOVED" -H "Authorization: Bearer $SAT"
DSTATUS=$(jq -r --arg f "$FQDN2" '[.content[] | select(.fqdn==$f)][0].status // empty' "$B")
DREL=$(jq -r --arg f "$FQDN2" '[.content[] | select(.fqdn==$f)][0].releasedAt // empty' "$B")
[ "$DSTATUS" = "REMOVED" ] && ok "second DELETE returned the reserved name (REMOVED)" || ko "reserved row not REMOVED after second DELETE (status=$DSTATUS)"
[ -z "$DREL" ] && ok "returned name carries no release stamp" || ko "release stamp survived the return ($DREL)"

echo "== platform subdomain cap (settings-driven, not hardcoded) =="
req "sysadmin login" 200 -X POST "$BASE/auth/login" -H 'Content-Type: application/json' -d "{\"email\":\"$SYSADMIN_EMAIL\",\"password\":\"$SYSADMIN_PW\"}" || true
XAT=$(jq -r .accessToken "$B")
curl -sS -o "$B" "$BASE/admin/settings" -H "Authorization: Bearer $XAT"
# No DB row means the server falls back to its code default (3) — mirror that.
LIMIT=$(jq -r '[.[] | select(.key=="platform_subdomains_per_vm")][0].value // 3' "$B")
if [ "$LIMIT" -le 10 ] 2>/dev/null; then
  curl -sS -o "$B" "$BASE/vms/$VM" -H "Authorization: Bearer $SAT"
  CUR=$(jq -r '[.publications[] | select(.domain.kind != "CUSTOM")] | length' "$B")
  ok "cap=$LIMIT, serving platform subdomains now=$CUR"
  i=0
  while [ $((CUR+i)) -lt "$LIMIT" ]; do
    i=$((i+1))
    req "cap filler $i" 202 -X POST "$BASE/vms/$VM/domains" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"port\":80,\"subdomain\":\"${SUB}-cap${i}\",\"rootDomain\":\"$ROOT\"}" || break
  done
  req "cap exceeded answers 409" 409 -X POST "$BASE/vms/$VM/domains" -H "Authorization: Bearer $SAT" -H 'Content-Type: application/json' -d "{\"port\":80,\"subdomain\":\"${SUB}-over\",\"rootDomain\":\"$ROOT\"}" || true
  [ "$(jq -r '.code // empty' "$B")" = "DOMAIN_LIMIT_REACHED" ] && ok "cap error code = DOMAIN_LIMIT_REACHED" || ko "cap error code = $(jq -r '.code' "$B")"
else
  echo "-- cap check skipped: platform_subdomains_per_vm=$LIMIT is too large for a smoke fill --"
fi

echo "== teardown on delete: force-delete → EVERY vhost removed =="
req "force-delete" 202 -X POST "$BASE/admin/vms/$VM/force-delete" -H "Authorization: Bearer $XAT" -H 'Content-Type: application/json' -d "{\"confirmName\":\"$VNAME\",\"reason\":\"http e2e cleanup\"}" || true
# poll until GET /vms/{id} 404s or status=DELETED (http code, not jq-on-error-body)
DL=$((SECONDS+180)); DC=""; DST=""
while :; do
  DC=$(curl -sS -o "$B" -w '%{http_code}' "$BASE/vms/$VM" -H "Authorization: Bearer $XAT" 2>/dev/null)
  DST=$(jq -r '.status // empty' "$B" 2>/dev/null)
  { [ "$DC" = "404" ] || [ "$DST" = "DELETED" ]; } && break
  [ "$SECONDS" -ge "$DL" ] && break; sleep 10; done
{ [ "$DC" = "404" ] || [ "$DST" = "DELETED" ]; } && ok "VM deleted (http=$DC${DST:+ status=$DST})" || ko "VM not deleted in 180s (http=$DC status=$DST)"
{ [ "$DC" = "404" ] || [ "$DST" = "DELETED" ]; } && VM_DELETED=1
# The API hides the VM as soon as the delete is accepted, but the teardown runs
# inside the async delete pipeline (teardown → destroy → mark deleted) — so poll
# the vhosts' disappearance with a deadline instead of a single snapshot. Every
# domain this run created (first, second, cap fillers) carries the $SUB prefix,
# so one count covers the WHOLE set: deletion must tear down all of them.
TDL=$((SECONDS+120)); VCNT="?"
while :; do
  VCNT=$(vhost_count "$SUB")
  [ "$VCNT" = "0" ] && break
  [ "$SECONDS" -ge "$TDL" ] && break; sleep 5; done
[ "$VCNT" = "0" ] && ok "all vhosts removed after delete (teardown)" || ko "stale vhost(s) remain after 120s (count=$VCNT)"
# re-check via the origin :443 SNI path (the external FQDN can't be curled from
# pve-node — hairpin NAT — so `!=200` there would be vacuously true). -k on purpose:
# a cert error must not mask a stale vhost still serving the VM content.
# NOTE: an HTTP 200 here is EXPECTED after teardown — with the vhost gone the SNI
# falls through to the default 8443 server (the console), which answers 200. The
# meaningful assertion is the VM marker's absence (+ the pickle.d count above).
if [ -n "$FQDN1" ]; then
  : >"$B"
  C=$(curl -sS -o "$B" -w '%{http_code}' -k --max-time 15 --resolve "$FQDN1:443:198.18.1.10" "https://$FQDN1/index.html" 2>/dev/null)
  # Two outcomes are correct after teardown, and both have to be told apart from
  # a check that merely failed to reach anything.
  #
  # Since the reverse proxy gained a reject default server, the removed name is
  # an unknown SNI and the handshake is refused outright — curl reports 000 with
  # a TLS-level error. That is the strongest possible teardown result, so accept
  # it, but only when curl actually says the handshake was rejected: a network
  # failure also yields 000 and must not read as success.
  #
  # Otherwise a response must genuinely arrive before "the marker is absent"
  # means anything. An empty body or a connect failure used to satisfy that test
  # just as well and was reported as a successful teardown.
  # Captured, not piped: curl exits non-zero when it refuses, and under
  # `pipefail` that would sink the whole pipeline regardless of what grep found.
  TLS_ERR=$(curl -sS -o /dev/null -k --max-time 15 \
       --resolve "$FQDN1:443:198.18.1.10" "https://$FQDN1/index.html" 2>&1 || true)
  if [ "$C" = 000 ] && printf '%s' "$TLS_ERR" | grep -qiE 'ssl|tls|handshake'; then
    ok "origin refuses the removed name at the TLS handshake after teardown"
  elif ! [[ "$C" =~ ^[1-5][0-9][0-9]$ ]]; then
    ko "teardown origin check: no HTTP response and no TLS refusal (curl code $C)"
  elif [ ! -s "$B" ]; then
    ko "teardown origin check: HTTP $C with an empty body — nothing to assert on"
  elif grep -q "PICKLE-HTTP-E2E-OK" "$B"; then
    ko "origin still serves VM content after delete ($C)"
  else
    ok "origin answered $C without the VM marker after teardown"
  fi
else
  ko "teardown origin check (no FQDN)"
fi

echo; echo "HTTP-PUBLISH E2E: $P passed / $((P+F)) checks"
[ "$F" -eq 0 ] && exit 0 || exit 1
